### Listar todas as tarefas
GET http://localhost:5273/api/tarefas/listar

### Cadastrar uma nova tarefa
POST http://localhost:5273/api/tarefas/cadastrar
Content-Type: application/json

{
    "titulo": "Estudar Node.js"
}

### api/tarefa/alterar - Alterar uma tarefa
PUT http://localhost:5273/api/tarefas/alterar/6a8b3e4d-5e4e-4f7e-bdc9-9181e456ad0e

###  Listar tarefas não concluídas
GET http://localhost:5273/api/tarefas/naoconcluidas

### 🟢 Listar tarefas concluídas
GET http://localhost:5273/api/tarefas/concluidas

###