### Listar todas as tarefas
GET http://localhost:5000/api/tarefas/listar

### Cadastrar uma nova tarefa
POST http://localhost:5000/api/tarefas/cadastrar
Content-Type: application/json

{
    "titulo": "Estudar Node.js"
}

### api/tarefa/alterar - Alterar uma tarefa
PUT http://localhost:5000/api/tarefas/alterar/2f1b7dc1-3b9a-4e1a-a389-7f5d2f1c8f3e

###  Listar tarefas não concluídas
GET http://localhost:5000/api/tarefas/naoconcluidas

### 🟢 Listar tarefas concluídas
GET http://localhost:5000/api/tarefas/concluidas

###